#!/bin/bash
action-set info.host="$(hostname)" info.message="Hello $(action-get who)!"
action-log hello sailor
echo Goodbye cruel world
echo This message goes to stderr >&2
echo Foo bar
for i in {1..10}
do
   action-log "Welcome $i times"
   sleep 1
done
exit 3
